### ISSUE TITLE
Design a Random Name Generator with Gender

### ISSUE THREAD

**Issue by Jayesh-JainX** [Jayesh-JainX/Hacktoberfest-23#10]

**Comment by insane-22** [comment]
Hello, I am interested in working on this issue, Could you please assign me this issue? 
I would appreciate it if you could brief me about the exact functionality required.
Thank you for your consideration

**Comment by Jayesh-JainX** [comment]
Sure @insane-22
You can create a website where users can generate random names along with their gender (Male/Female). Your code should be capable of generating 100 different names along with their corresponding genders. This website can be a useful tool for various purposes like creating test data, character names, or any application that requires random name generation with associated genders.

**Comment by insane-22** [comment]
Ok, got it!
Could you please assign the issue to me?

**Comment by Jayesh-JainX** [comment]
### Before we proceed, we kindly request you to:
- Star this Repository: ⭐ Starring the repository helps us reach a wider audience and encourages more contributions. You can star the repo by clicking the "Star" button at the top of this page.

- Follow the Code of Conduct: 📜 We maintain a [Code of Conduct](https://github.com/Jayesh-JainX/Hacktoberfest-23/blob/main/CONTRIBUTING.md) to ensure a positive and respectful environment for all contributors. Please review and abide by it throughout your involvement in this project.

***If you have any questions or need further assistance, feel free to ask. Happy coding! 🚀***

**Comment by Jayesh-JainX** [comment]
**Important Announcement:**

Dear Contributors,

I regret to inform you that our repository has been excluded from Hacktoberfest participation due to certain reasons. As a result, any contributions made to this repository during Hacktoberfest will not count towards the event.

We understand that many of you were eager to contribute to our project, and we sincerely apologize for any inconvenience this may cause. We value and appreciate your interest in our work.

If you're still interested in contributing to open source projects for Hacktoberfest, we encourage you to explore other repositories and communities that are participating in the event. There are many exciting projects out there that would greatly benefit from your contributions.

Once again, we apologize for any inconvenience and thank you for your understanding. We hope to welcome contributions to our repository in the future when it becomes eligible for such events.

Best regards,
[Jayesh Jain](https://github.com/Jayesh-JainX/)
