### ISSUE TITLE
Design a Text-to-Speech Converter

### ISSUE THREAD

**Issue by Jayesh-JainX** [Jayesh-JainX/Hacktoberfest-23#12]

**Comment by ombhagwat2401** [comment]
Hello @Jayesh-JainX I would like to contribute to this task.

Can you please assign me this task?

**Comment by Jayesh-JainX** [comment]
hey @ombhagwat2401,
only one issue can be assign at a time.

**Comment by r0ld3x** [comment]
@Jayesh-JainX Assign me :) 

i will use NextJs

**Comment by Jayesh-JainX** [comment]
###  Before we proceed, we kindly request you to:
- Star this Repository: ⭐ Starring the repository helps us reach a wider audience and encourages more contributions. You can star the repo by clicking the "Star" button at the top of this page.

- Follow the Code of Conduct: 📜 We maintain a Code a [Code of Conduct](https://github.com/Jayesh-JainX/Hacktoberfest-23/blob/main/CONTRIBUTING.md) to ensure a positive and respectful environment for all contributors. Please review and abide by it throughout your involvement in this project.

- Add Your Profile Details: 📋 You can find instructions on how to add your profile details to the repository in our [YouTube Video](https://youtu.be/xweXYoeNkoA?feature=shared). Please follow the steps outlined in the video to complete this task before contributing.

***If you have any questions or need further assistance, feel free to ask. Happy coding! 🚀***

**Comment by r0ld3x** [comment]
ok working on it

**Comment by r0ld3x** [comment]
@Jayesh-JainX merge it please

**Comment by Jayesh-JainX** [comment]
**Important Announcement:**

Dear Contributors,

I regret to inform you that our repository has been excluded from Hacktoberfest participation due to certain reasons. As a result, any contributions made to this repository during Hacktoberfest will not count towards the event.

We understand that many of you were eager to contribute to our project, and we sincerely apologize for any inconvenience this may cause. We value and appreciate your interest in our work.

If you're still interested in contributing to open source projects for Hacktoberfest, we encourage you to explore other repositories and communities that are participating in the event. There are many exciting projects out there that would greatly benefit from your contributions.

Once again, we apologize for any inconvenience and thank you for your understanding. We hope to welcome contributions to our repository in the future when it becomes eligible for such events.

Best regards,
[Jayesh Jain](https://github.com/Jayesh-JainX/)
