### ISSUE TITLE
Create a To-Do List App

### ISSUE THREAD

**Issue by Jayesh-JainX** [Jayesh-JainX/Hacktoberfest-23#16]

**Comment by chiku011** [comment]
Hello, I would like to request assignment to the to-do list app issue as I believe I can make a meaningful contribution to the project

**Comment by Jayesh-JainX** [comment]
### Before we proceed, we kindly request you to:
- Star this Repository: ⭐ Starring the repository helps us reach a wider audience and encourages more contributions. You can star the repo by clicking the "Star" button at the top of this page.

- Follow the Code of Conduct: 📜 We maintain a [Code of Conduct](https://github.com/Jayesh-JainX/Hacktoberfest-23/blob/main/CONTRIBUTING.md) to ensure a positive and respectful environment for all contributors. Please review and abide by it throughout your involvement in this project.

***If you have any questions or need further assistance, feel free to ask. Happy coding! 🚀***

**Comment by Manish12-verma** [comment]
Hey,please assign this issue to me under hacktoberfest 2023
