### ISSUE TITLE
Implement a Calculator using Java (Scientific Calculator)

### ISSUE THREAD

**Issue by Jayesh-JainX** [Jayesh-JainX/Hacktoberfest-23#6]

**Comment by MohdYousufDev** [comment]
Here is a Simple code for that to follow 

import java.util.Scanner;
import java.lang.Math;

public class ScientificCalculator {

    public static void main(String[] args) {
        Scanner scanner = new Scanner(System.in);

        while (true) {
            printMenu();
            int choice = scanner.nextInt();

            if (choice == 9) {
                System.out.println("Exiting the calculator.");
                break;
            }

            double result = performOperation(choice, scanner);
            System.out.println("Result: " + result);
        }

        scanner.close();
    }

    private static void printMenu() {
        System.out.println("Scientific Calculator");
        System.out.println("1. Addition");
        System.out.println("2. Subtraction");
        System.out.println("3. Multiplication");
        System.out.println("4. Division");
        System.out.println("5. Square Root");
        System.out.println("6. Sine");
        System.out.println("7. Cosine");
        System.out.println("8. Tangent");
        System.out.println("9. Exit");
        System.out.print("Select an option: ");
    }

    private static double performOperation(int choice, Scanner scanner) {
        double result = 0.0;

        switch (choice) {
            case 1:
                result = performAddition(scanner);
                break;
            case 2:
                result = performSubtraction(scanner);
                break;
            case 3:
                result = performMultiplication(scanner);
                break;
            case 4:
                result = performDivision(scanner);
                break;
            case 5:
                result = performSquareRoot(scanner);
                break;
            case 6:
                result = performSine(scanner);
                break;
            case 7:
                result = performCosine(scanner);
                break;
            case 8:
                result = performTangent(scanner);
                break;
            default:
                System.out.println("Invalid choice. Please try again.");
        }

        return result;
    }

    private static double performAddition(Scanner scanner) {
        System.out.print("Enter first number: ");
        double addend1 = scanner.nextDouble();
        System.out.print("Enter second number: ");
        double addend2 = scanner.nextDouble();
        return addend1 + addend2;
    }

    private static double performSubtraction(Scanner scanner) {
        System.out.print("Enter minuend: ");
        double minuend = scanner.nextDouble();
        System.out.print("Enter subtrahend: ");
        double subtrahend = scanner.nextDouble();
        return minuend - subtrahend;
    }

    private static double performMultiplication(Scanner scanner) {
        System.out.print("Enter first number: ");
        double factor1 = scanner.nextDouble();
        System.out.print("Enter second number: ");
        double factor2 = scanner.nextDouble();
        return factor1 * factor2;
    }

    private static double performDivision(Scanner scanner) {
        System.out.print("Enter dividend: ");
        double dividend = scanner.nextDouble();
        System.out.print("Enter divisor: ");
        double divisor = scanner.nextDouble();
        if (divisor != 0) {
            return dividend / divisor;
        } else {
            System.out.println("Division by zero is not allowed.");
            return 0.0;
        }
    }

    private static double performSquareRoot(Scanner scanner) {
        System.out.print("Enter a number: ");
        double number = scanner.nextDouble();
        if (number >= 0) {
            return Math.sqrt(number);
        } else {
            System.out.println("Square root of a negative number is not allowed.");
            return 0.0;
        }
    }

    private static double performSine(Scanner scanner) {
        System.out.print("Enter an angle in degrees: ");
        double angle = scanner.nextDouble();
        return Math.sin(Math.toRadians(angle));
    }

    private static double performCosine(Scanner scanner) {
        System.out.print("Enter an angle in degrees: ");
        double angle = scanner.nextDouble();
        return Math.cos(Math.toRadians(angle));
    }

    private static double performTangent(Scanner scanner) {
        System.out.print("Enter an angle in degrees: ");
        double angle = scanner.nextDouble();
        return Math.tan(Math.toRadians(angle));
    }
}

**Comment by Jayesh-JainX** [comment]
@MohdYousufDev 
the program is basic java program, 
implement using Swing
should be not copied from other source.

**Comment by Neel-07** [comment]
Hello @Jayesh-JainX , can you assign me this issue i want to work on this as i have prior knowledge in java and i think i can contribute to it. Thank you  for your consideration.

**Comment by Jayesh-JainX** [comment]
**Important Announcement:**

Dear Contributors,

I regret to inform you that our repository has been excluded from Hacktoberfest participation due to certain reasons. As a result, any contributions made to this repository during Hacktoberfest will not count towards the event.

We understand that many of you were eager to contribute to our project, and we sincerely apologize for any inconvenience this may cause. We value and appreciate your interest in our work.

If you're still interested in contributing to open source projects for Hacktoberfest, we encourage you to explore other repositories and communities that are participating in the event. There are many exciting projects out there that would greatly benefit from your contributions.

Once again, we apologize for any inconvenience and thank you for your understanding. We hope to welcome contributions to our repository in the future when it becomes eligible for such events.

Best regards,
[Jayesh Jain](https://github.com/Jayesh-JainX/)
