### ISSUE TITLE
Develop a Currency Exchange Rate Checker

### ISSUE THREAD

**Issue by Jayesh-JainX** [Jayesh-JainX/Hacktoberfest-23#9]

**Comment by Rhythm-08** [comment]
Hello @Jayesh-JainX  can you assign this task to me I want to work on it

**Comment by Jayesh-JainX** [comment]
@Rhythm-08 ,
can you make a web page that can check rates?

**Comment by Rhythm-08** [comment]
Sure I can make a webpage in angular, 
Requirements is to make a currency converter.

**Comment by Jayesh-JainX** [comment]
### Before we proceed, we kindly request you to:
- Star this Repository: ⭐ Starring the repository helps us reach a wider audience and encourages more contributions. You can star the repo by clicking the "Star" button at the top of this page.

- Follow the Code of Conduct: 📜 We maintain a [Code of Conduct](https://github.com/Jayesh-JainX/Hacktoberfest-23/blob/main/CONTRIBUTING.md) to ensure a positive and respectful environment for all contributors. Please review and abide by it throughout your involvement in this project.

***If you have any questions or need further assistance, feel free to ask. Happy coding! 🚀***

**Comment by Jayesh-JainX** [comment]
**Important Announcement:**

Dear Contributors,

I regret to inform you that our repository has been excluded from Hacktoberfest participation due to certain reasons. As a result, any contributions made to this repository during Hacktoberfest will not count towards the event.

We understand that many of you were eager to contribute to our project, and we sincerely apologize for any inconvenience this may cause. We value and appreciate your interest in our work.

If you're still interested in contributing to open source projects for Hacktoberfest, we encourage you to explore other repositories and communities that are participating in the event. There are many exciting projects out there that would greatly benefit from your contributions.

Once again, we apologize for any inconvenience and thank you for your understanding. We hope to welcome contributions to our repository in the future when it becomes eligible for such events.

Best regards,
[Jayesh Jain](https://github.com/Jayesh-JainX/)
